# Generated by Django 4.0 on 2022-02-09 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='duyuru')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IstekOneri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adsoyad', models.CharField(max_length=30)),
                ('acıklama', models.TextField(max_length=300)),
                ('numara', models.CharField(blank=True, max_length=11, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='istekoneri')),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Responser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resp', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tcno', models.CharField(blank=True, default=None, max_length=11, null=True)),
                ('name_surname', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('gender', models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadın')], max_length=128, null=True)),
                ('birth_date', models.CharField(blank=True, max_length=12, null=True)),
                ('job', models.CharField(blank=True, max_length=30, null=True)),
                ('birth_city', models.CharField(blank=True, max_length=20, null=True)),
                ('father', models.CharField(blank=True, max_length=40, null=True)),
                ('mother', models.CharField(blank=True, max_length=40, null=True)),
                ('son', models.CharField(blank=True, max_length=40, null=True)),
                ('daughter', models.CharField(blank=True, max_length=40, null=True)),
                ('living_city', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.CharField(blank=True, max_length=60, null=True)),
                ('create_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('update_time', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='İsimsiz Kullanıcı', max_length=30)),
                ('phone', models.TextField(default='Yok', max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('desc', models.TextField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
