# Generated by Django 4.0 on 2022-02-10 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_announcement_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='istekoneri',
            name='image',
        ),
    ]
